### ISSUE TITLE
Not an issue, just a question...

### ISSUE THREAD

**Issue by AkosMaster** [apekros/valorant_offsets#3]
Hello apekros! I have recently finished my own external Valorant cheat, however I would like to ask you how did you get these offsets? I would like to automatize it myself instead of downloading them from here all the time!

Thanks for the repostory, hope you can help my noob ass.

**Comment by apekros** [comment]
Using names and objects you can grab offsets for classes e.g damage handler
world/names/engine/objects I just have sigged them.

**Comment by AkosMaster** [comment]
yeah but what tool did you use?

**Comment by apekros** [comment]
Something I wrote myself.

**Comment by AkosMaster** [comment]
can you link some good sources (not necessarily code) so I can write one myself?Sent from my Samsung device

-------- Original message --------

**Comment by apekros** [comment]
Look at previous games that have more information on them that also use UE4.
