### ISSUE TITLE
Help with addresses

### ISSUE THREAD

**Issue by ghost** [apekros/valorant_offsets#4]
I tried to search and find addresses , but after updating it does not work, please help me with this , I will be very grateful to you !!!
`
char* drawBuff = (char*)malloc(1024);
D3DXVECTOR4 Rect;

uint64_t world;
uint64_t persistent_level;
uint64_t game_instance;
uint64_t local_player_array;
uint64_t local_player;
uint64_t local_player_controller;
uint64_t local_player_pawn;
uint64_t damage_controller;
float health;
uint64_t camera_manager;
Vector3 camera_position;
Vector3 camera_rotation;
float camera_fov;
uint64_t actors;
int actor_count;
Vector3 LocalPos;
uint64_t LocalRoot;

void cache()
{
	while (true)
	{
		vector<TslEntity> tmpList;

		world = read<std::uint64_t>(m_base + 0x5d07df8);
		persistent_level = read<std::uint64_t>(world + 0x38);
		game_instance = read<std::uint64_t>(world + 0x190);

		local_player_array = read<std::uint64_t>(game_instance + 0x40);
		local_player = read<std::uint64_t>(local_player_array);
		local_player_controller = read<std::uint64_t>(local_player + 0x38);
		local_player_pawn = read<std::uint64_t>(local_player_controller + 0x518);

		camera_manager = read<std::uint64_t>(local_player_controller + 0x530);

		actors = read<std::uint64_t>(persistent_level + 0xA0);
		actor_count = read<int>(persistent_level + 0xA8);

		LocalRoot = read<std::uint64_t>(local_player_pawn + 0x238);
		LocalPos = read<Vector3>(LocalRoot + 0x1E0);

		damage_controller = read<std::uint64_t>(local_player_pawn + 0xa38);

		for (unsigned long i = 0; i < actor_count; ++i)
		{
			std::uint64_t actor = read<std::uint64_t>(actors + i * 0x8);

			if (actor == 0x00)
			{
				continue;
			}

			

			int ID = read<int>(actor + 0x18);

			TslEntity tslEntity{ };
			tslEntity.pObjPointer = actor;
			tslEntity.ID = ID;
			tslEntity.PlayerController = local_player_controller;

			uint64_t mesh = read<uint64_t>(actor + 0x408);

			int UniqueID = read<int>(actor + 0x3C);
			if (UniqueID != 16777502)
				continue;

			if (mesh != 0x00 && UniqueID != 0x00)
			{
				tslEntity.mesh = mesh;

				tmpList.push_back(tslEntity);
			}
		}
		entityList = tmpList;
		Sleep(1);
	}
}

void ESP() {

	int revise = 0;
	auto entityListCopy = entityList;
	float distance = 0.f;

	if (entityListCopy.empty())
	{
		return;
	}

	for (unsigned long i = 0; i < entityListCopy.size(); ++i)
	{
		TslEntity entity = entityListCopy[i];
		bool is_alive = read<bool>(damage_controller + 0x425);
		health = read<float>(damage_controller + 0x1B0);

		if (entity.pObjPointer == local_player_pawn)
		{
			continue;
		}

		if (entity.pObjPointer == is_alive)
		{
			continue;
		}

		

		camera_position = read<Vector3>(camera_manager + 0x1260);

		camera_rotation = read<Vector3>(camera_manager + 0x126C);
		camera_fov = read<float>(camera_manager + 0x4B0) + 33.0f;

		auto root_component = read<std::uint64_t>(entity.pObjPointer + 0x238);
		auto RootPos = read<Vector3>(root_component + 0x1E0);

		wchar_t pPlayerName[64] = { NULL };

		auto ActorPlayerState = read<uint64_t>(entity.pObjPointer + 0x4B0);

		readwtf(ActorPlayerState + 0x490, &pPlayerName, sizeof(pPlayerName));

		uint64_t mesh = entity.mesh;

		distance = LocalPos.Distance(RootPos) / 100.f;

		if (mesh != 0x00)
		{
			Vector3 vHeadBone = GetBoneWithRotation(mesh, 8);
			Vector3 RootPos2d = WorldToScreen(RootPos, camera_position, camera_rotation, camera_fov);

			sprintf(drawBuff, u8" %s %0.fm ", pPlayerName, distance);

			if (vHeadBone.z <= RootPos.z)
				continue;

			revise = strlen(drawBuff) * 7 + 28;
			DrawFilledRect(RootPos2d.x - (revise / 2) + (Rect.w / 2) - 1, RootPos2d.y + Rect.z - 25, revise + 1, 3, &Col.blue);
			DrawFilledRect(RootPos2d.x - (revise / 2) + (Rect.w / 2) - 1, RootPos2d.y + Rect.z - 28, revise + 1, 16, &Col.blue);
			DrawNewText(RootPos2d.x - (revise / 2) + (Rect.w / 2) + 21, RootPos2d.y + Rect.z - 27, &Col.white_, drawBuff);

			if (health >= 100)
				health = 100;
			int length = (int)(health * revise / 100);

			if (health >= 80)
				DrawFilledRect(RootPos2d.x - (revise / 2) + (Rect.w / 2), RootPos2d.y + Rect.z - 13, length, 1, &Col.greens_);
			else if (health < 80 && health > 50)
				DrawFilledRect(RootPos2d.x - (revise / 2) + (Rect.w / 2), RootPos2d.y + Rect.z - 13, length, 1, &Col.red_);
			else if (health <= 50)
				DrawFilledRect(RootPos2d.x - (revise / 2) + (Rect.w / 2), RootPos2d.y + Rect.z - 13, length, 1, &Col.gray_);
		}
	}
}
`
This is the function code , can you tell me which addresses are incorrect and what their values are now

**Comment by apekros** [comment]
world is wrong. I'm not going to debug your code for you.
